package vn.linh.tracker.util.constant

const val REQUEST_CODE_RUNTIME_PERMISSION = 0x1
const val REQUEST_CODE_LOCATION_SETTINGS = 0x2
const val REQUEST_CODE_GOOGLE_SIGN_IN = 0x3
const val REQUEST_CODE_FITNESS_PERMISSION = 0x4
